on: [pull_request]

name: Test

concurrency:
  # Cancel older, in-progress jobs from the same PR, same workflow.
  # use run_id if the job is triggered by a push to ensure
  # push-triggered jobs to not get canceled.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
    linting:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[dev]

        - name: Run linter
          run: ruff check

        - name: Run format check
          run: ruff format --check --diff

    type-check:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: "3.10"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[dev]

        - name: Run MyPy
          run: mypy .

    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
              python-version: ${{ matrix.python-version }}

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[dev]

        - name: Run Tests
          run: pytest
